### ISSUE TITLE
E-Com Plus auth client

### ISSUE THREAD

**Issue by leomp12** [ecomclub/ecomplus-auth#1]
## TODO

- [x] Constructor based JS lib;
- [x] Use `@ecomplus/client` to consume Store API;
- [x] Take [`ecomplus-passport-client`](https://github.com/ecomclub/ecomplus-passport-client) as example for methods and events;

**Comment by leomp12** [comment]
Related issue https://github.com/ecomclub/admin-marketplace/issues/1
